export const SET_PRESENT_CONSISTS_CHECKBOX = 'SET_PRESENT_CONSISTS_CHECKBOX'
export const SET_PURPOSES_CHECKBOX = 'SET_PURPOSES_CHECKBOX'
export const SET_PACKAGES_CHECKBOX = 'SET_PACKAGES_CHECKBOX'
export const SET_SORT_SELECT = 'SET_SORT_SELECT'
export const DECREMENT_PRODUCT_COUNT = 'DECREMENT_PRODUCT_COUNT'
export const INCREMENT_PRODUCT_COUNT = 'INCREMENT_PRODUCT_COUNT'
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const SET_IS_USER_AUTH = 'SET_IS_USER_AUTH'
export const CHANGE_USER_INFO = 'CHANGE_USER_INFO'





