export const SET_PRESENT_CONSISTS_CHECKBOX = 'SET_PRESENT_CONSISTS_CHECKBOX'
export const SET_PURPOSES_CHECKBOX = 'SET_PURPOSES_CHECKBOX'
export const SET_PACKAGES_CHECKBOX = 'SET_PACKAGES_CHECKBOX'
export const SET_SORT_SELECT = 'SET_SORT_SELECT'
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED'
export const CHANGE_USER_INFO = 'CHANGE_USER_INFO'




// ProductsReducer -----------------------------------------------------------------------
export const DECREMENT_PRODUCT_COUNT = 'DECREMENT_PRODUCT_COUNT'
export const INCREMENT_PRODUCT_COUNT = 'INCREMENT_PRODUCT_COUNT'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT'

// Cart
export const SET_CART_ITEMS = 'SET_CART_ITEMS'
export const SET_CARTS_PRODUCTS = 'SET_CARTS_PRODUCTS'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const CHANGE_CART_ITEM_QUANTITY = 'CHANGE_CART_ITEM_QUANTITY'
export const SET_COST = 'SET_COST'
export const SET_DISCOUNT = 'SET_DISCOUNT'


